### ISSUE TITLE
Create about page

### ISSUE THREAD

**Issue by bmmunga** [lapislazuli21/codedex-hackathon-track1#1]
**Description:**

- Develop an About page for the website.
- Include content about the organisation's story and values.
- Add an image that represents the organisation before the about section content.
- Ensure the content is styled to match a theme of "Sip & Play".

**Tasks:**

- [x] Develop the About page component.
- [x] Add an image before the content.
- [x] Include the organization’s story and values.
- [ ] Style the page to match the theme.
