### ISSUE TITLE
Set up styles

### ISSUE THREAD

**Issue by bmmunga** [lapislazuli21/codedex-hackathon-track1#2]
**Description:**

- Implement CSS to style the About page.
- Ensure the page has a playful and engaging font.
- Use the `Poppins` font to achieve the desired look and feel.

**Tasks:**

- [x] Import the `Poppins` font from Google Fonts.
- [x] Apply the font to the entire page.
- [ ] Style the image to be large and centered.
- [ ] Style the text content to be aligned and visually appealing.
